
package com.finsoft.g2pg.test.testwallet.service;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.jws.soap.SOAPBinding;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Action;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.1
 * Generated source version: 3.0
 * 
 */
@WebService(name = "TestWalletService", targetNamespace = "http://com.finsoft.g2pg")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface TestWalletService {


    /**
     * 
     * @param loginRequest
     * @return
     *     returns com.finsoft.g2pg.test.testwallet.service.LoginResponse
     */
    @WebMethod(operationName = "Login")
    @WebResult(name = "loginResponse", targetNamespace = "http://com.finsoft.g2pg", partName = "loginResponse")
    @Action(input = "http://com.finsoft.g2pg/TestWalletService/LoginRequest", output = "http://com.finsoft.g2pg/TestWalletService/LoginResponse")
    public LoginResponse login(
        @WebParam(name = "loginRequest", targetNamespace = "http://com.finsoft.g2pg", partName = "loginRequest")
        LoginRequest loginRequest);

//    /**
//     *
//     * @param temporarySessionIdRequest
//     * @return
//     *     returns com.igt.pay.testwallet.wallet.api.testwallet.TemporarySessionIdResponse
//     */
//    @WebMethod(operationName = "GenerateTemporarySessionId")
//    @WebResult(name = "temporarySessionIdResponse", targetNamespace = "http://com.finsoft.g2pg", partName = "temporarySessionIdResponse")
//    @Action(input = "http://com.finsoft.g2pg/TestWalletService/GenerateTemporarySessionIdRequest", output = "http://com.finsoft.g2pg/TestWalletService/GenerateTemporarySessionIdResponse")
//    public TemporarySessionIdResponse generateTemporarySessionId(
//        @WebParam(name = "temporarySessionIdRequest", targetNamespace = "http://com.finsoft.g2pg", partName = "temporarySessionIdRequest")
//        TemporarySessionIdRequest temporarySessionIdRequest);

}
